import axios from 'axios';

// ISO country data
const COUNTRIES = [
  { code: 'AD', name: 'Andorra', region: 'Europe', subregion: 'Southern Europe', flag_emoji: '🇦🇩', currency: 'EUR', currency_symbol: '€', language: 'Catalan', timezone: 'Europe/Andorra', calling_code: '+376' },
  { code: 'AE', name: 'United Arab Emirates', region: 'Asia', subregion: 'Western Asia', flag_emoji: '🇦🇪', currency: 'AED', currency_symbol: 'د.إ', language: 'Arabic', timezone: 'Asia/Dubai', calling_code: '+971' },
  { code: 'AF', name: 'Afghanistan', region: 'Asia', subregion: 'Central Asia', flag_emoji: '🇦🇫', currency: 'AFN', currency_symbol: '؋', language: 'Pashto', timezone: 'Asia/Kabul', calling_code: '+93' },
  { code: 'AG', name: 'Antigua and Barbuda', region: 'Americas', subregion: 'Caribbean', flag_emoji: '🇦🇬', currency: 'XCD', currency_symbol: '$', language: 'English', timezone: 'America/Antigua', calling_code: '+1-268' },
  { code: 'AL', name: 'Albania', region: 'Europe', subregion: 'Southern Europe', flag_emoji: '🇦🇱', currency: 'ALL', currency_symbol: 'L', language: 'Albanian', timezone: 'Europe/Tirane', calling_code: '+355' },
  { code: 'AM', name: 'Armenia', region: 'Asia', subregion: 'Western Asia', flag_emoji: '🇦🇲', currency: 'AMD', currency_symbol: '֏', language: 'Armenian', timezone: 'Asia/Yerevan', calling_code: '+374' },
  { code: 'AO', name: 'Angola', region: 'Africa', subregion: 'Middle Africa', flag_emoji: '🇦🇴', currency: 'AOA', currency_symbol: 'Kz', language: 'Portuguese', timezone: 'Africa/Luanda', calling_code: '+244' },
  { code: 'AR', name: 'Argentina', region: 'Americas', subregion: 'South America', flag_emoji: '🇦🇷', currency: 'ARS', currency_symbol: '$', language: 'Spanish', timezone: 'America/Argentina/Buenos_Aires', calling_code: '+54' },
  { code: 'AT', name: 'Austria', region: 'Europe', subregion: 'Western Europe', flag_emoji: '🇦🇹', currency: 'EUR', currency_symbol: '€', language: 'German', timezone: 'Europe/Vienna', calling_code: '+43' },
  { code: 'AU', name: 'Australia', region: 'Oceania', subregion: 'Australia and New Zealand', flag_emoji: '🇦🇺', currency: 'AUD', currency_symbol: '$', language: 'English', timezone: 'Australia/Sydney', calling_code: '+61' },
  { code: 'AZ', name: 'Azerbaijan', region: 'Asia', subregion: 'Western Asia', flag_emoji: '🇦🇿', currency: 'AZN', currency_symbol: '₼', language: 'Azerbaijani', timezone: 'Asia/Baku', calling_code: '+994' },
  { code: 'BA', name: 'Bosnia and Herzegovina', region: 'Europe', subregion: 'Southern Europe', flag_emoji: '🇧🇦', currency: 'BAM', currency_symbol: 'KM', language: 'Bosnian', timezone: 'Europe/Sarajevo', calling_code: '+387' },
  { code: 'BB', name: 'Barbados', region: 'Americas', subregion: 'Caribbean', flag_emoji: '🇧🇧', currency: 'BBD', currency_symbol: '$', language: 'English', timezone: 'America/Barbados', calling_code: '+1-246' },
  { code: 'BD', name: 'Bangladesh', region: 'Asia', subregion: 'South-Central Asia', flag_emoji: '🇧🇩', currency: 'BDT', currency_symbol: '৳', language: 'Bengali', timezone: 'Asia/Dhaka', calling_code: '+880' },
  { code: 'BE', name: 'Belgium', region: 'Europe', subregion: 'Western Europe', flag_emoji: '🇧🇪', currency: 'EUR', currency_symbol: '€', language: 'Dutch', timezone: 'Europe/Brussels', calling_code: '+32' },
  { code: 'BG', name: 'Bulgaria', region: 'Europe', subregion: 'Eastern Europe', flag_emoji: '🇧🇬', currency: 'BGN', currency_symbol: 'лв', language: 'Bulgarian', timezone: 'Europe/Sofia', calling_code: '+359' },
  { code: 'BH', name: 'Bahrain', region: 'Asia', subregion: 'Western Asia', flag_emoji: '🇧🇭', currency: 'BHD', currency_symbol: '.د.ب', language: 'Arabic', timezone: 'Asia/Bahrain', calling_code: '+973' },
  { code: 'BI', name: 'Burundi', region: 'Africa', subregion: 'Eastern Africa', flag_emoji: '🇧🇮', currency: 'BIF', currency_symbol: 'FBu', language: 'Kirundi', timezone: 'Africa/Bujumbura', calling_code: '+257' },
  { code: 'BJ', name: 'Benin', region: 'Africa', subregion: 'West Africa', flag_emoji: '🇧🇯', currency: 'XOF', currency_symbol: 'CFA', language: 'French', timezone: 'Africa/Porto-Novo', calling_code: '+229' },
  { code: 'BN', name: 'Brunei', region: 'Asia', subregion: 'South-Eastern Asia', flag_emoji: '🇧🇳', currency: 'BND', currency_symbol: '$', language: 'Malay', timezone: 'Asia/Brunei', calling_code: '+673' },
  { code: 'BO', name: 'Bolivia', region: 'Americas', subregion: 'South America', flag_emoji: '🇧🇴', currency: 'BOB', currency_symbol: 'Bs.', language: 'Spanish', timezone: 'America/La_Paz', calling_code: '+591' },
  { code: 'BR', name: 'Brazil', region: 'Americas', subregion: 'South America', flag_emoji: '🇧🇷', currency: 'BRL', currency_symbol: 'R$', language: 'Portuguese', timezone: 'America/Sao_Paulo', calling_code: '+55' },
  { code: 'BS', name: 'Bahamas', region: 'Americas', subregion: 'Caribbean', flag_emoji: '🇧🇸', currency: 'BSD', currency_symbol: '$', language: 'English', timezone: 'America/Nassau', calling_code: '+1-242' },
  { code: 'BT', name: 'Bhutan', region: 'Asia', subregion: 'South-Central Asia', flag_emoji: '🇧🇹', currency: 'BTN', currency_symbol: 'Nu.', language: 'Dzongkha', timezone: 'Asia/Thimphu', calling_code: '+975' },
  { code: 'BW', name: 'Botswana', region: 'Africa', subregion: 'Southern Africa', flag_emoji: '🇧🇼', currency: 'BWP', currency_symbol: 'P', language: 'English', timezone: 'Africa/Gaborone', calling_code: '+267' },
  { code: 'BY', name: 'Belarus', region: 'Europe', subregion: 'Eastern Europe', flag_emoji: '🇧🇾', currency: 'BYN', currency_symbol: 'Br', language: 'Belarusian', timezone: 'Europe/Minsk', calling_code: '+375' },
  { code: 'BZ', name: 'Belize', region: 'Americas', subregion: 'Central America', flag_emoji: '🇧🇿', currency: 'BZD', currency_symbol: '$', language: 'English', timezone: 'America/Belize', calling_code: '+501' },
  { code: 'CA', name: 'Canada', region: 'Americas', subregion: 'Northern America', flag_emoji: '🇨🇦', currency: 'CAD', currency_symbol: '$', language: 'English', timezone: 'America/Toronto', calling_code: '+1' },
  { code: 'CD', name: 'Democratic Republic of the Congo', region: 'Africa', subregion: 'Middle Africa', flag_emoji: '🇨🇩', currency: 'CDF', currency_symbol: 'FC', language: 'French', timezone: 'Africa/Kinshasa', calling_code: '+243' },
  { code: 'CF', name: 'Central African Republic', region: 'Africa', subregion: 'Middle Africa', flag_emoji: '🇨🇫', currency: 'XAF', currency_symbol: 'FCFA', language: 'French', timezone: 'Africa/Bangui', calling_code: '+236' },
  { code: 'CG', name: 'Republic of the Congo', region: 'Africa', subregion: 'Middle Africa', flag_emoji: '🇨🇬', currency: 'XAF', currency_symbol: 'CFA', language: 'French', timezone: 'Africa/Brazzaville', calling_code: '+242' },
  { code: 'CH', name: 'Switzerland', region: 'Europe', subregion: 'Western Europe', flag_emoji: '🇨🇭', currency: 'CHF', currency_symbol: 'Fr', language: 'German', timezone: 'Europe/Zurich', calling_code: '+41' },
  { code: 'CI', name: "Cote d'Ivoire", region: 'Africa', subregion: 'West Africa', flag_emoji: '🇨🇮', currency: 'XOF', currency_symbol: 'CFA', language: 'French', timezone: 'Africa/Abidjan', calling_code: '+225' },
  { code: 'CL', name: 'Chile', region: 'Americas', subregion: 'South America', flag_emoji: '🇨🇱', currency: 'CLP', currency_symbol: '$', language: 'Spanish', timezone: 'America/Santiago', calling_code: '+56' },
  { code: 'CM', name: 'Cameroon', region: 'Africa', subregion: 'Middle Africa', flag_emoji: '🇨🇲', currency: 'XAF', currency_symbol: 'FCFA', language: 'French', timezone: 'Africa/Douala', calling_code: '+237' },
  { code: 'CN', name: 'China', region: 'Asia', subregion: 'Eastern Asia', flag_emoji: '🇨🇳', currency: 'CNY', currency_symbol: '¥', language: 'Mandarin', timezone: 'Asia/Shanghai', calling_code: '+86' },
  { code: 'CO', name: 'Colombia', region: 'Americas', subregion: 'South America', flag_emoji: '🇨🇴', currency: 'COP', currency_symbol: '$', language: 'Spanish', timezone: 'America/Bogota', calling_code: '+57' },
  { code: 'CR', name: 'Costa Rica', region: 'Americas', subregion: 'Central America', flag_emoji: '🇨🇷', currency: 'CRC', currency_symbol: '₡', language: 'Spanish', timezone: 'America/Costa_Rica', calling_code: '+506' },
  { code: 'CU', name: 'Cuba', region: 'Americas', subregion: 'Caribbean', flag_emoji: '🇨🇺', currency: 'CUP', currency_symbol: '₱', language: 'Spanish', timezone: 'America/Havana', calling_code: '+53' },
  { code: 'CV', name: 'Cape Verde', region: 'Africa', subregion: 'West Africa', flag_emoji: '🇨🇻', currency: 'CVE', currency_symbol: '$', language: 'Portuguese', timezone: 'Atlantic/Cape_Verde', calling_code: '+238' },
  { code: 'CY', name: 'Cyprus', region: 'Europe', subregion: 'Southern Europe', flag_emoji: '🇨🇾', currency: 'EUR', currency_symbol: '€', language: 'Greek', timezone: 'Asia/Nicosia', calling_code: '+357' },
  { code: 'CZ', name: 'Czech Republic', region: 'Europe', subregion: 'Eastern Europe', flag_emoji: '🇨🇿', currency: 'CZK', currency_symbol: 'Kč', language: 'Czech', timezone: 'Europe/Prague', calling_code: '+420' },
  { code: 'DE', name: 'Germany', region: 'Europe', subregion: 'Western Europe', flag_emoji: '🇩🇪', currency: 'EUR', currency_symbol: '€', language: 'German', timezone: 'Europe/Berlin', calling_code: '+49' },
  { code: 'DJ', name: 'Djibouti', region: 'Africa', subregion: 'Eastern Africa', flag_emoji: '🇩🇯', currency: 'DJF', currency_symbol: 'Fdj', language: 'French', timezone: 'Africa/Djibouti', calling_code: '+253' },
  { code: 'DK', name: 'Denmark', region: 'Europe', subregion: 'Northern Europe', flag_emoji: '🇩🇰', currency: 'DKK', currency_symbol: 'kr', language: 'Danish', timezone: 'Europe/Copenhagen', calling_code: '+45' },
  { code: 'DM', name: 'Dominica', region: 'Americas', subregion: 'Caribbean', flag_emoji: '🇩🇲', currency: 'XCD', currency_symbol: '$', language: 'English', timezone: 'America/Dominica', calling_code: '+1-767' },
  { code: 'DO', name: 'Dominican Republic', region: 'Americas', subregion: 'Caribbean', flag_emoji: '🇩🇴', currency: 'DOP', currency_symbol: '$', language: 'Spanish', timezone: 'America/Santo_Domingo', calling_code: '+1-809' },
  { code: 'DZ', name: 'Algeria', region: 'Africa', subregion: 'Northern Africa', flag_emoji: '🇩🇿', currency: 'DZD', currency_symbol: 'د.ج', language: 'Arabic', timezone: 'Africa/Algiers', calling_code: '+213' },
  { code: 'EC', name: 'Ecuador', region: 'Americas', subregion: 'South America', flag_emoji: '🇪🇨', currency: 'USD', currency_symbol: '$', language: 'Spanish', timezone: 'America/Guayaquil', calling_code: '+593' },
  { code: 'EE', name: 'Estonia', region: 'Europe', subregion: 'Northern Europe', flag_emoji: '🇪🇪', currency: 'EUR', currency_symbol: '€', language: 'Estonian', timezone: 'Europe/Tallinn', calling_code: '+372' },
  { code: 'EG', name: 'Egypt', region: 'Africa', subregion: 'Northern Africa', flag_emoji: '🇪🇬', currency: 'EGP', currency_symbol: 'E£', language: 'Arabic', timezone: 'Africa/Cairo', calling_code: '+20' },
  { code: 'ER', name: 'Eritrea', region: 'Africa', subregion: 'Eastern Africa', flag_emoji: '🇪🇷', currency: 'ERN', currency_symbol: 'Nfk', language: 'Tigrinya', timezone: 'Africa/Asmara', calling_code: '+291' },
  { code: 'ES', name: 'Spain', region: 'Europe', subregion: 'Southern Europe', flag_emoji: '🇪🇸', currency: 'EUR', currency_symbol: '€', language: 'Spanish', timezone: 'Europe/Madrid', calling_code: '+34' },
  { code: 'ET', name: 'Ethiopia', region: 'Africa', subregion: 'Eastern Africa', flag_emoji: '🇪🇹', currency: 'ETB', currency_symbol: 'Br', language: 'Amharic', timezone: 'Africa/Addis_Ababa', calling_code: '+251' },
  { code: 'FI', name: 'Finland', region: 'Europe', subregion: 'Northern Europe', flag_emoji: '🇫🇮', currency: 'EUR', currency_symbol: '€', language: 'Finnish', timezone: 'Europe/Helsinki', calling_code: '+358' },
  { code: 'FJ', name: 'Fiji', region: 'Oceania', subregion: 'Melanesia', flag_emoji: '🇫🇯', currency: 'FJD', currency_symbol: '$', language: 'English', timezone: 'Pacific/Fiji', calling_code: '+679' },
  { code: 'FM', name: 'Micronesia', region: 'Oceania', subregion: 'Micronesia', flag_emoji: '🇫🇲', currency: 'USD', currency_symbol: '$', language: 'English', timezone: 'Pacific/Pohnpei', calling_code: '+691' },
  { code: 'FR', name: 'France', region: 'Europe', subregion: 'Western Europe', flag_emoji: '🇫🇷', currency: 'EUR', currency_symbol: '€', language: 'French', timezone: 'Europe/Paris', calling_code: '+33' },
  { code: 'GA', name: 'Gabon', region: 'Africa', subregion: 'Middle Africa', flag_emoji: '🇬🇦', currency: 'XAF', currency_symbol: 'FCFA', language: 'French', timezone: 'Africa/Libreville', calling_code: '+241' },
  { code: 'GB', name: 'United Kingdom', region: 'Europe', subregion: 'Northern Europe', flag_emoji: '🇬🇧', currency: 'GBP', currency_symbol: '£', language: 'English', timezone: 'Europe/London', calling_code: '+44' },
  { code: 'GD', name: 'Grenada', region: 'Americas', subregion: 'Caribbean', flag_emoji: '🇬🇩', currency: 'XCD', currency_symbol: '$', language: 'English', timezone: 'America/Grenada', calling_code: '+1-473' },
  { code: 'GE', name: 'Georgia', region: 'Asia', subregion: 'Western Asia', flag_emoji: '🇬🇪', currency: 'GEL', currency_symbol: '₾', language: 'Georgian', timezone: 'Asia/Tbilisi', calling_code: '+995' },
  { code: 'GH', name: 'Ghana', region: 'Africa', subregion: 'West Africa', flag_emoji: '🇬🇭', currency: 'GHS', currency_symbol: '₵', language: 'English', timezone: 'Africa/Accra', calling_code: '+233' },
  { code: 'GM', name: 'Gambia', region: 'Africa', subregion: 'West Africa', flag_emoji: '🇬🇲', currency: 'GMD', currency_symbol: 'D', language: 'English', timezone: 'Africa/Banjul', calling_code: '+220' },
  { code: 'GN', name: 'Guinea', region: 'Africa', subregion: 'West Africa', flag_emoji: '🇬🇳', currency: 'GNF', currency_symbol: 'FG', language: 'French', timezone: 'Africa/Conakry', calling_code: '+224' },
  { code: 'GQ', name: 'Equatorial Guinea', region: 'Africa', subregion: 'Middle Africa', flag_emoji: '🇬🇶', currency: 'XAF', currency_symbol: 'FCFA', language: 'Spanish', timezone: 'Africa/Malabo', calling_code: '+240' },
  { code: 'GR', name: 'Greece', region: 'Europe', subregion: 'Southern Europe', flag_emoji: '🇬🇷', currency: 'EUR', currency_symbol: '€', language: 'Greek', timezone: 'Europe/Athens', calling_code: '+30' },
  { code: 'GT', name: 'Guatemala', region: 'Americas', subregion: 'Central America', flag_emoji: '🇬🇹', currency: 'GTQ', currency_symbol: 'Q', language: 'Spanish', timezone: 'America/Guatemala', calling_code: '+502' },
  { code: 'GW', name: 'Guinea-Bissau', region: 'Africa', subregion: 'West Africa', flag_emoji: '🇬🇼', currency: 'XOF', currency_symbol: 'CFA', language: 'Portuguese', timezone: 'Africa/Bissau', calling_code: '+245' },
  { code: 'GY', name: 'Guyana', region: 'Americas', subregion: 'South America', flag_emoji: '🇬🇾', currency: 'GYD', currency_symbol: '$', language: 'English', timezone: 'America/Guyana', calling_code: '+592' },
  { code: 'HN', name: 'Honduras', region: 'Americas', subregion: 'Central America', flag_emoji: '🇭🇳', currency: 'HNL', currency_symbol: 'L', language: 'Spanish', timezone: 'America/Tegucigalpa', calling_code: '+504' },
  { code: 'HR', name: 'Croatia', region: 'Europe', subregion: 'Southern Europe', flag_emoji: '🇭🇷', currency: 'EUR', currency_symbol: '€', language: 'Croatian', timezone: 'Europe/Zagreb', calling_code: '+385' },
  { code: 'HT', name: 'Haiti', region: 'Americas', subregion: 'Caribbean', flag_emoji: '🇭🇹', currency: 'HTG', currency_symbol: 'G', language: 'French', timezone: 'America/Port-au-Prince', calling_code: '+509' },
  { code: 'HU', name: 'Hungary', region: 'Europe', subregion: 'Eastern Europe', flag_emoji: '🇭🇺', currency: 'HUF', currency_symbol: 'Ft', language: 'Hungarian', timezone: 'Europe/Budapest', calling_code: '+36' },
  { code: 'ID', name: 'Indonesia', region: 'Asia', subregion: 'South-Eastern Asia', flag_emoji: '🇮🇩', currency: 'IDR', currency_symbol: 'Rp', language: 'Indonesian', timezone: 'Asia/Jakarta', calling_code: '+62' },
  { code: 'IE', name: 'Ireland', region: 'Europe', subregion: 'Northern Europe', flag_emoji: '🇮🇪', currency: 'EUR', currency_symbol: '€', language: 'English', timezone: 'Europe/Dublin', calling_code: '+353' },
  { code: 'IL', name: 'Israel', region: 'Asia', subregion: 'Western Asia', flag_emoji: '🇮🇱', currency: 'ILS', currency_symbol: '₪', language: 'Hebrew', timezone: 'Asia/Jerusalem', calling_code: '+972' },
  { code: 'IN', name: 'India', region: 'Asia', subregion: 'South-Central Asia', flag_emoji: '🇮🇳', currency: 'INR', currency_symbol: '₹', language: 'Hindi', timezone: 'Asia/Kolkata', calling_code: '+91' },
  { code: 'IQ', name: 'Iraq', region: 'Asia', subregion: 'Western Asia', flag_emoji: '🇮🇶', currency: 'IQD', currency_symbol: 'ع.د', language: 'Arabic', timezone: 'Asia/Baghdad', calling_code: '+964' },
  { code: 'IR', name: 'Iran', region: 'Asia', subregion: 'South-Central Asia', flag_emoji: '🇮🇷', currency: 'IRR', currency_symbol: '﷼', language: 'Persian', timezone: 'Asia/Tehran', calling_code: '+98' },
  { code: 'IS', name: 'Iceland', region: 'Europe', subregion: 'Northern Europe', flag_emoji: '🇮🇸', currency: 'ISK', currency_symbol: 'kr', language: 'Icelandic', timezone: 'Atlantic/Reykjavik', calling_code: '+354' },
  { code: 'IT', name: 'Italy', region: 'Europe', subregion: 'Southern Europe', flag_emoji: '🇮🇹', currency: 'EUR', currency_symbol: '€', language: 'Italian', timezone: 'Europe/Rome', calling_code: '+39' },
  { code: 'JM', name: 'Jamaica', region: 'Americas', subregion: 'Caribbean', flag_emoji: '🇯🇲', currency: 'JMD', currency_symbol: '$', language: 'English', timezone: 'America/Jamaica', calling_code: '+1-876' },
  { code: 'JO', name: 'Jordan', region: 'Asia', subregion: 'Western Asia', flag_emoji: '🇯🇴', currency: 'JOD', currency_symbol: 'د.ا', language: 'Arabic', timezone: 'Asia/Amman', calling_code: '+962' },
  { code: 'JP', name: 'Japan', region: 'Asia', subregion: 'Eastern Asia', flag_emoji: '🇯🇵', currency: 'JPY', currency_symbol: '¥', language: 'Japanese', timezone: 'Asia/Tokyo', calling_code: '+81' },
  { code: 'KE', name: 'Kenya', region: 'Africa', subregion: 'Eastern Africa', flag_emoji: '🇰🇪', currency: 'KES', currency_symbol: 'KSh', language: 'Swahili', timezone: 'Africa/Nairobi', calling_code: '+254' },
  { code: 'KG', name: 'Kyrgyzstan', region: 'Asia', subregion: 'Central Asia', flag_emoji: '🇰🇬', currency: 'KGS', currency_symbol: 'лв', language: 'Kyrgyz', timezone: 'Asia/Bishkek', calling_code: '+996' },
  { code: 'KH', name: 'Cambodia', region: 'Asia', subregion: 'South-Eastern Asia', flag_emoji: '🇰🇭', currency: 'KHR', currency_symbol: '៛', language: 'Khmer', timezone: 'Asia/Phnom_Penh', calling_code: '+855' },
  { code: 'KI', name: 'Kiribati', region: 'Oceania', subregion: 'Micronesia', flag_emoji: '🇰🇮', currency: 'AUD', currency_symbol: '$', language: 'English', timezone: 'Pacific/Tarawa', calling_code: '+686' },
  { code: 'KM', name: 'Comoros', region: 'Africa', subregion: 'Eastern Africa', flag_emoji: '🇰🇲', currency: 'KMF', currency_symbol: 'CF', language: 'French', timezone: 'Indian/Comoro', calling_code: '+269' },
  { code: 'KN', name: 'Saint Kitts and Nevis', region: 'Americas', subregion: 'Caribbean', flag_emoji: '🇰🇳', currency: 'XCD', currency_symbol: '$', language: 'English', timezone: 'America/St_Kitts', calling_code: '+1-869' },
  { code: 'KP', name: 'North Korea', region: 'Asia', subregion: 'Eastern Asia', flag_emoji: '🇰🇵', currency: 'KPW', currency_symbol: '₩', language: 'Korean', timezone: 'Asia/Pyongyang', calling_code: '+850' },
  { code: 'KR', name: 'South Korea', region: 'Asia', subregion: 'Eastern Asia', flag_emoji: '🇰🇷', currency: 'KRW', currency_symbol: '₩', language: 'Korean', timezone: 'Asia/Seoul', calling_code: '+82' },
  { code: 'KW', name: 'Kuwait', region: 'Asia', subregion: 'Western Asia', flag_emoji: '🇰🇼', currency: 'KWD', currency_symbol: 'د.ك', language: 'Arabic', timezone: 'Asia/Kuwait', calling_code: '+965' },
  { code: 'KZ', name: 'Kazakhstan', region: 'Asia', subregion: 'Central Asia', flag_emoji: '🇰🇿', currency: 'KZT', currency_symbol: '₸', language: 'Kazakh', timezone: 'Asia/Almaty', calling_code: '+7' },
  { code: 'LA', name: 'Laos', region: 'Asia', subregion: 'South-Eastern Asia', flag_emoji: '🇱🇦', currency: 'LAK', currency_symbol: '₭', language: 'Lao', timezone: 'Asia/Vientiane', calling_code: '+856' },
  { code: 'LB', name: 'Lebanon', region: 'Asia', subregion: 'Western Asia', flag_emoji: '🇱🇧', currency: 'LBP', currency_symbol: 'ل.ل', language: 'Arabic', timezone: 'Asia/Beirut', calling_code: '+961' },
  { code: 'LC', name: 'Saint Lucia', region: 'Americas', subregion: 'Caribbean', flag_emoji: '🇱🇨', currency: 'XCD', currency_symbol: '$', language: 'English', timezone: 'America/St_Lucia', calling_code: '+1-758' },
  { code: 'LI', name: 'Liechtenstein', region: 'Europe', subregion: 'Western Europe', flag_emoji: '🇱🇮', currency: 'CHF', currency_symbol: 'Fr', language: 'German', timezone: 'Europe/Vaduz', calling_code: '+423' },
  { code: 'LK', name: 'Sri Lanka', region: 'Asia', subregion: 'South-Central Asia', flag_emoji: '🇱🇰', currency: 'LKR', currency_symbol: 'Rs', language: 'Sinhala', timezone: 'Asia/Colombo', calling_code: '+94' },
  { code: 'LR', name: 'Liberia', region: 'Africa', subregion: 'West Africa', flag_emoji: '🇱🇷', currency: 'LRD', currency_symbol: '$', language: 'English', timezone: 'Africa/Monrovia', calling_code: '+231' },
  { code: 'LS', name: 'Lesotho', region: 'Africa', subregion: 'Southern Africa', flag_emoji: '🇱🇸', currency: 'LSL', currency_symbol: 'L', language: 'Sesotho', timezone: 'Africa/Maseru', calling_code: '+266' },
  { code: 'LT', name: 'Lithuania', region: 'Europe', subregion: 'Northern Europe', flag_emoji: '🇱🇹', currency: 'EUR', currency_symbol: '€', language: 'Lithuanian', timezone: 'Europe/Vilnius', calling_code: '+370' },
  { code: 'LU', name: 'Luxembourg', region: 'Europe', subregion: 'Western Europe', flag_emoji: '🇱🇺', currency: 'EUR', currency_symbol: '€', language: 'French', timezone: 'Europe/Luxembourg', calling_code: '+352' },
  { code: 'LV', name: 'Latvia', region: 'Europe', subregion: 'Northern Europe', flag_emoji: '🇱🇻', currency: 'EUR', currency_symbol: '€', language: 'Latvian', timezone: 'Europe/Riga', calling_code: '+371' },
  { code: 'LY', name: 'Libya', region: 'Africa', subregion: 'Northern Africa', flag_emoji: '🇱🇾', currency: 'LYD', currency_symbol: 'ل.د', language: 'Arabic', timezone: 'Africa/Tripoli', calling_code: '+218' },
  { code: 'MA', name: 'Morocco', region: 'Africa', subregion: 'Northern Africa', flag_emoji: '🇲🇦', currency: 'MAD', currency_symbol: 'د.م.', language: 'Arabic', timezone: 'Africa/Casablanca', calling_code: '+212' },
  { code: 'MC', name: 'Monaco', region: 'Europe', subregion: 'Western Europe', flag_emoji: '🇲🇨', currency: 'EUR', currency_symbol: '€', language: 'French', timezone: 'Europe/Monaco', calling_code: '+377' },
  { code: 'MD', name: 'Moldova', region: 'Europe', subregion: 'Eastern Europe', flag_emoji: '🇲🇩', currency: 'MDL', currency_symbol: 'L', language: 'Romanian', timezone: 'Europe/Chisinau', calling_code: '+373' },
  { code: 'ME', name: 'Montenegro', region: 'Europe', subregion: 'Southern Europe', flag_emoji: '🇲🇪', currency: 'EUR', currency_symbol: '€', language: 'Montenegrin', timezone: 'Europe/Podgorica', calling_code: '+382' },
  { code: 'MG', name: 'Madagascar', region: 'Africa', subregion: 'Eastern Africa', flag_emoji: '🇲🇬', currency: 'MGA', currency_symbol: 'Ar', language: 'Malagasy', timezone: 'Indian/Antananarivo', calling_code: '+261' },
  { code: 'MH', name: 'Marshall Islands', region: 'Oceania', subregion: 'Micronesia', flag_emoji: '🇲🇭', currency: 'USD', currency_symbol: '$', language: 'English', timezone: 'Pacific/Majuro', calling_code: '+692' },
  { code: 'MK', name: 'North Macedonia', region: 'Europe', subregion: 'Southern Europe', flag_emoji: '🇲🇰', currency: 'MKD', currency_symbol: 'ден', language: 'Macedonian', timezone: 'Europe/Skopje', calling_code: '+389' },
  { code: 'ML', name: 'Mali', region: 'Africa', subregion: 'West Africa', flag_emoji: '🇲🇱', currency: 'XOF', currency_symbol: 'CFA', language: 'French', timezone: 'Africa/Bamako', calling_code: '+223' },
  { code: 'MM', name: 'Myanmar', region: 'Asia', subregion: 'South-Eastern Asia', flag_emoji: '🇲🇲', currency: 'MMK', currency_symbol: 'K', language: 'Burmese', timezone: 'Asia/Yangon', calling_code: '+95' },
  { code: 'MN', name: 'Mongolia', region: 'Asia', subregion: 'Eastern Asia', flag_emoji: '🇲🇳', currency: 'MNT', currency_symbol: '₮', language: 'Mongolian', timezone: 'Asia/Ulaanbaatar', calling_code: '+976' },
  { code: 'MR', name: 'Mauritania', region: 'Africa', subregion: 'West Africa', flag_emoji: '🇲🇷', currency: 'MRO', currency_symbol: 'UM', language: 'Arabic', timezone: 'Africa/Nouakchott', calling_code: '+222' },
  { code: 'MT', name: 'Malta', region: 'Europe', subregion: 'Southern Europe', flag_emoji: '🇲🇹', currency: 'EUR', currency_symbol: '€', language: 'Maltese', timezone: 'Europe/Malta', calling_code: '+356' },
  { code: 'MU', name: 'Mauritius', region: 'Africa', subregion: 'Eastern Africa', flag_emoji: '🇲🇺', currency: 'MUR', currency_symbol: '₹', language: 'English', timezone: 'Indian/Mauritius', calling_code: '+230' },
  { code: 'MV', name: 'Maldives', region: 'Asia', subregion: 'South-Central Asia', flag_emoji: '🇲🇻', currency: 'MVR', currency_symbol: 'Rf', language: 'Dhivehi', timezone: 'Indian/Maldives', calling_code: '+960' },
  { code: 'MW', name: 'Malawi', region: 'Africa', subregion: 'Eastern Africa', flag_emoji: '🇲🇼', currency: 'MWK', currency_symbol: 'MK', language: 'English', timezone: 'Africa/Blantyre', calling_code: '+265' },
  { code: 'MX', name: 'Mexico', region: 'Americas', subregion: 'Central America', flag_emoji: '🇲🇽', currency: 'MXN', currency_symbol: '$', language: 'Spanish', timezone: 'America/Mexico_City', calling_code: '+52' },
  { code: 'MY', name: 'Malaysia', region: 'Asia', subregion: 'South-Eastern Asia', flag_emoji: '🇲🇾', currency: 'MYR', currency_symbol: 'RM', language: 'Malay', timezone: 'Asia/Kuala_Lumpur', calling_code: '+60' },
  { code: 'MZ', name: 'Mozambique', region: 'Africa', subregion: 'Eastern Africa', flag_emoji: '🇲🇿', currency: 'MZN', currency_symbol: 'MT', language: 'Portuguese', timezone: 'Africa/Maputo', calling_code: '+258' },
  { code: 'NA', name: 'Namibia', region: 'Africa', subregion: 'Southern Africa', flag_emoji: '🇳🇦', currency: 'NAD', currency_symbol: '$', language: 'English', timezone: 'Africa/Windhoek', calling_code: '+264' },
  { code: 'NE', name: 'Niger', region: 'Africa', subregion: 'West Africa', flag_emoji: '🇳🇪', currency: 'XOF', currency_symbol: 'CFA', language: 'French', timezone: 'Africa/Niamey', calling_code: '+227' },
  { code: 'NG', name: 'Nigeria', region: 'Africa', subregion: 'West Africa', flag_emoji: '🇳🇬', currency: 'NGN', currency_symbol: '₦', language: 'English', timezone: 'Africa/Lagos', calling_code: '+234' },
  { code: 'NI', name: 'Nicaragua', region: 'Americas', subregion: 'Central America', flag_emoji: '🇳🇮', currency: 'NIO', currency_symbol: 'C$', language: 'Spanish', timezone: 'America/Managua', calling_code: '+505' },
  { code: 'NL', name: 'Netherlands', region: 'Europe', subregion: 'Western Europe', flag_emoji: '🇳🇱', currency: 'EUR', currency_symbol: '€', language: 'Dutch', timezone: 'Europe/Amsterdam', calling_code: '+31' },
  { code: 'NO', name: 'Norway', region: 'Europe', subregion: 'Northern Europe', flag_emoji: '🇳🇴', currency: 'NOK', currency_symbol: 'kr', language: 'Norwegian', timezone: 'Europe/Oslo', calling_code: '+47' },
  { code: 'NP', name: 'Nepal', region: 'Asia', subregion: 'South-Central Asia', flag_emoji: '🇳🇵', currency: 'NPR', currency_symbol: '₽', language: 'Nepali', timezone: 'Asia/Kathmandu', calling_code: '+977' },
  { code: 'NR', name: 'Nauru', region: 'Oceania', subregion: 'Micronesia', flag_emoji: '🇳🇷', currency: 'AUD', currency_symbol: '$', language: 'Nauruan', timezone: 'Pacific/Nauru', calling_code: '+674' },
  { code: 'NZ', name: 'New Zealand', region: 'Oceania', subregion: 'Australia and New Zealand', flag_emoji: '🇳🇿', currency: 'NZD', currency_symbol: '$', language: 'English', timezone: 'Pacific/Auckland', calling_code: '+64' },
  { code: 'OM', name: 'Oman', region: 'Asia', subregion: 'Western Asia', flag_emoji: '🇴🇲', currency: 'OMR', currency_symbol: 'ر.ع.', language: 'Arabic', timezone: 'Asia/Muscat', calling_code: '+968' },
  { code: 'PA', name: 'Panama', region: 'Americas', subregion: 'Central America', flag_emoji: '🇵🇦', currency: 'PAB', currency_symbol: 'B/.', language: 'Spanish', timezone: 'America/Panama', calling_code: '+507' },
  { code: 'PE', name: 'Peru', region: 'Americas', subregion: 'South America', flag_emoji: '🇵🇪', currency: 'PEN', currency_symbol: 'S/.', language: 'Spanish', timezone: 'America/Lima', calling_code: '+51' },
  { code: 'PG', name: 'Papua New Guinea', region: 'Oceania', subregion: 'Melanesia', flag_emoji: '🇵🇬', currency: 'PGK', currency_symbol: 'K', language: 'English', timezone: 'Pacific/Port_Moresby', calling_code: '+675' },
  { code: 'PH', name: 'Philippines', region: 'Asia', subregion: 'South-Eastern Asia', flag_emoji: '🇵🇭', currency: 'PHP', currency_symbol: '₱', language: 'Filipino', timezone: 'Asia/Manila', calling_code: '+63' },
  { code: 'PK', name: 'Pakistan', region: 'Asia', subregion: 'South-Central Asia', flag_emoji: '🇵🇰', currency: 'PKR', currency_symbol: '₨', language: 'Urdu', timezone: 'Asia/Karachi', calling_code: '+92' },
  { code: 'PL', name: 'Poland', region: 'Europe', subregion: 'Eastern Europe', flag_emoji: '🇵🇱', currency: 'PLN', currency_symbol: 'zł', language: 'Polish', timezone: 'Europe/Warsaw', calling_code: '+48' },
  { code: 'PT', name: 'Portugal', region: 'Europe', subregion: 'Southern Europe', flag_emoji: '🇵🇹', currency: 'EUR', currency_symbol: '€', language: 'Portuguese', timezone: 'Europe/Lisbon', calling_code: '+351' },
  { code: 'PW', name: 'Palau', region: 'Oceania', subregion: 'Micronesia', flag_emoji: '🇵🇼', currency: 'USD', currency_symbol: '$', language: 'English', timezone: 'Pacific/Palau', calling_code: '+680' },
  { code: 'PY', name: 'Paraguay', region: 'Americas', subregion: 'South America', flag_emoji: '🇵🇾', currency: 'PYG', currency_symbol: '₲', language: 'Spanish', timezone: 'America/Asuncion', calling_code: '+595' },
  { code: 'QA', name: 'Qatar', region: 'Asia', subregion: 'Western Asia', flag_emoji: '🇶🇦', currency: 'QAR', currency_symbol: 'ر.ق', language: 'Arabic', timezone: 'Asia/Qatar', calling_code: '+974' },
  { code: 'RO', name: 'Romania', region: 'Europe', subregion: 'Eastern Europe', flag_emoji: '🇷🇴', currency: 'RON', currency_symbol: 'lei', language: 'Romanian', timezone: 'Europe/Bucharest', calling_code: '+40' },
  { code: 'RS', name: 'Serbia', region: 'Europe', subregion: 'Southern Europe', flag_emoji: '🇷🇸', currency: 'RSD', currency_symbol: 'дин.', language: 'Serbian', timezone: 'Europe/Belgrade', calling_code: '+381' },
  { code: 'RU', name: 'Russia', region: 'Europe', subregion: 'Eastern Europe', flag_emoji: '🇷🇺', currency: 'RUB', currency_symbol: '₽', language: 'Russian', timezone: 'Europe/Moscow', calling_code: '+7' },
  { code: 'RW', name: 'Rwanda', region: 'Africa', subregion: 'Eastern Africa', flag_emoji: '🇷🇼', currency: 'RWF', currency_symbol: 'FRw', language: 'Kinyarwanda', timezone: 'Africa/Kigali', calling_code: '+250' },
  { code: 'SA', name: 'Saudi Arabia', region: 'Asia', subregion: 'Western Asia', flag_emoji: '🇸🇦', currency: 'SAR', currency_symbol: 'ر.س', language: 'Arabic', timezone: 'Asia/Riyadh', calling_code: '+966' },
  { code: 'SB', name: 'Solomon Islands', region: 'Oceania', subregion: 'Melanesia', flag_emoji: '🇸🇧', currency: 'SBD', currency_symbol: '$', language: 'English', timezone: 'Pacific/Guadalcanal', calling_code: '+677' },
  { code: 'SC', name: 'Seychelles', region: 'Africa', subregion: 'Eastern Africa', flag_emoji: '🇸🇨', currency: 'SCR', currency_symbol: '₨', language: 'French', timezone: 'Indian/Mahe', calling_code: '+248' },
  { code: 'SD', name: 'Sudan', region: 'Africa', subregion: 'Northern Africa', flag_emoji: '🇸🇩', currency: 'SDG', currency_symbol: 'ج.س.', language: 'Arabic', timezone: 'Africa/Khartoum', calling_code: '+249' },
  { code: 'SE', name: 'Sweden', region: 'Europe', subregion: 'Northern Europe', flag_emoji: '🇸🇪', currency: 'SEK', currency_symbol: 'kr', language: 'Swedish', timezone: 'Europe/Stockholm', calling_code: '+46' },
  { code: 'SG', name: 'Singapore', region: 'Asia', subregion: 'South-Eastern Asia', flag_emoji: '🇸🇬', currency: 'SGD', currency_symbol: '$', language: 'English', timezone: 'Asia/Singapore', calling_code: '+65' },
  { code: 'SI', name: 'Slovenia', region: 'Europe', subregion: 'Southern Europe', flag_emoji: '🇸🇮', currency: 'EUR', currency_symbol: '€', language: 'Slovenian', timezone: 'Europe/Ljubljana', calling_code: '+386' },
  { code: 'SK', name: 'Slovakia', region: 'Europe', subregion: 'Eastern Europe', flag_emoji: '🇸🇰', currency: 'EUR', currency_symbol: '€', language: 'Slovak', timezone: 'Europe/Bratislava', calling_code: '+421' },
  { code: 'SL', name: 'Sierra Leone', region: 'Africa', subregion: 'West Africa', flag_emoji: '🇸🇱', currency: 'SLL', currency_symbol: 'Le', language: 'English', timezone: 'Africa/Freetown', calling_code: '+232' },
  { code: 'SM', name: 'San Marino', region: 'Europe', subregion: 'Southern Europe', flag_emoji: '🇸🇲', currency: 'EUR', currency_symbol: '€', language: 'Italian', timezone: 'Europe/San_Marino', calling_code: '+378' },
  { code: 'SN', name: 'Senegal', region: 'Africa', subregion: 'West Africa', flag_emoji: '🇸🇳', currency: 'XOF', currency_symbol: 'CFA', language: 'French', timezone: 'Africa/Dakar', calling_code: '+221' },
  { code: 'SO', name: 'Somalia', region: 'Africa', subregion: 'Eastern Africa', flag_emoji: '🇸🇴', currency: 'SOS', currency_symbol: 'S', language: 'Somali', timezone: 'Africa/Mogadishu', calling_code: '+252' },
  { code: 'SR', name: 'Suriname', region: 'Americas', subregion: 'South America', flag_emoji: '🇸🇷', currency: 'SRD', currency_symbol: '$', language: 'Dutch', timezone: 'America/Paramaribo', calling_code: '+597' },
  { code: 'SS', name: 'South Sudan', region: 'Africa', subregion: 'Eastern Africa', flag_emoji: '🇸🇸', currency: 'SSP', currency_symbol: '£', language: 'English', timezone: 'Africa/Juba', calling_code: '+211' },
  { code: 'SV', name: 'El Salvador', region: 'Americas', subregion: 'Central America', flag_emoji: '🇸🇻', currency: 'USD', currency_symbol: '$', language: 'Spanish', timezone: 'America/El_Salvador', calling_code: '+503' },
  { code: 'SY', name: 'Syria', region: 'Asia', subregion: 'Western Asia', flag_emoji: '🇸🇾', currency: 'SYP', currency_symbol: '£', language: 'Arabic', timezone: 'Asia/Damascus', calling_code: '+963' },
  { code: 'SZ', name: 'Eswatini', region: 'Africa', subregion: 'Southern Africa', flag_emoji: '🇸🇿', currency: 'SZL', currency_symbol: 'L', language: 'Swazi', timezone: 'Africa/Mbabane', calling_code: '+268' },
  { code: 'TD', name: 'Chad', region: 'Africa', subregion: 'Middle Africa', flag_emoji: '🇹🇩', currency: 'XAF', currency_symbol: 'FCFA', language: 'French', timezone: 'Africa/Ndjamena', calling_code: '+235' },
  { code: 'TG', name: 'Togo', region: 'Africa', subregion: 'West Africa', flag_emoji: '🇹🇬', currency: 'XOF', currency_symbol: 'CFA', language: 'French', timezone: 'Africa/Lome', calling_code: '+228' },
  { code: 'TH', name: 'Thailand', region: 'Asia', subregion: 'South-Eastern Asia', flag_emoji: '🇹🇭', currency: 'THB', currency_symbol: '฿', language: 'Thai', timezone: 'Asia/Bangkok', calling_code: '+66' },
  { code: 'TJ', name: 'Tajikistan', region: 'Asia', subregion: 'Central Asia', flag_emoji: '🇹🇯', currency: 'TJS', currency_symbol: 'SM', language: 'Tajik', timezone: 'Asia/Dushanbe', calling_code: '+992' },
  { code: 'TL', name: 'Timor-Leste', region: 'Asia', subregion: 'South-Eastern Asia', flag_emoji: '🇹🇱', currency: 'USD', currency_symbol: '$', language: 'Portuguese', timezone: 'Asia/Dili', calling_code: '+670' },
  { code: 'TM', name: 'Turkmenistan', region: 'Asia', subregion: 'Central Asia', flag_emoji: '🇹🇲', currency: 'TMT', currency_symbol: 'T', language: 'Turkmen', timezone: 'Asia/Ashgabat', calling_code: '+993' },
  { code: 'TN', name: 'Tunisia', region: 'Africa', subregion: 'Northern Africa', flag_emoji: '🇹🇳', currency: 'TND', currency_symbol: 'د.ت', language: 'Arabic', timezone: 'Africa/Tunis', calling_code: '+216' },
  { code: 'TO', name: 'Tonga', region: 'Oceania', subregion: 'Polynesia', flag_emoji: '🇹🇴', currency: 'TOP', currency_symbol: 'T$', language: 'Tongan', timezone: 'Pacific/Tongatapu', calling_code: '+676' },
  { code: 'TR', name: 'Turkey', region: 'Asia', subregion: 'Western Asia', flag_emoji: '🇹🇷', currency: 'TRY', currency_symbol: '₺', language: 'Turkish', timezone: 'Europe/Istanbul', calling_code: '+90' },
  { code: 'TT', name: 'Trinidad and Tobago', region: 'Americas', subregion: 'Caribbean', flag_emoji: '🇹🇹', currency: 'TTD', currency_symbol: '$', language: 'English', timezone: 'America/Port_of_Spain', calling_code: '+1-868' },
  { code: 'TV', name: 'Tuvalu', region: 'Oceania', subregion: 'Polynesia', flag_emoji: '🇹🇻', currency: 'AUD', currency_symbol: '$', language: 'Tuvaluan', timezone: 'Pacific/Funafuti', calling_code: '+688' },
  { code: 'TW', name: 'Taiwan', region: 'Asia', subregion: 'Eastern Asia', flag_emoji: '🇹🇼', currency: 'TWD', currency_symbol: 'NT$', language: 'Chinese', timezone: 'Asia/Taipei', calling_code: '+886' },
  { code: 'TZ', name: 'Tanzania', region: 'Africa', subregion: 'Eastern Africa', flag_emoji: '🇹🇿', currency: 'TZS', currency_symbol: 'TSh', language: 'Swahili', timezone: 'Africa/Dar_es_Salaam', calling_code: '+255' },
  { code: 'UA', name: 'Ukraine', region: 'Europe', subregion: 'Eastern Europe', flag_emoji: '🇺🇦', currency: 'UAH', currency_symbol: '₴', language: 'Ukrainian', timezone: 'Europe/Kiev', calling_code: '+380' },
  { code: 'UG', name: 'Uganda', region: 'Africa', subregion: 'Eastern Africa', flag_emoji: '🇺🇬', currency: 'UGX', currency_symbol: 'USh', language: 'English', timezone: 'Africa/Kampala', calling_code: '+256' },
  { code: 'US', name: 'United States', region: 'Americas', subregion: 'Northern America', flag_emoji: '🇺🇸', currency: 'USD', currency_symbol: '$', language: 'English', timezone: 'America/New_York', calling_code: '+1' },
  { code: 'UY', name: 'Uruguay', region: 'Americas', subregion: 'South America', flag_emoji: '🇺🇾', currency: 'UYU', currency_symbol: '$U', language: 'Spanish', timezone: 'America/Montevideo', calling_code: '+598' },
  { code: 'UZ', name: 'Uzbekistan', region: 'Asia', subregion: 'Central Asia', flag_emoji: '🇺🇿', currency: 'UZS', currency_symbol: 'лв', language: 'Uzbek', timezone: 'Asia/Samarkand', calling_code: '+998' },
  { code: 'VA', name: 'Vatican City', region: 'Europe', subregion: 'Southern Europe', flag_emoji: '🇻🇦', currency: 'EUR', currency_symbol: '€', language: 'Latin', timezone: 'Europe/Vatican', calling_code: '+379' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', region: 'Americas', subregion: 'Caribbean', flag_emoji: '🇻🇨', currency: 'XCD', currency_symbol: '$', language: 'English', timezone: 'America/St_Vincent', calling_code: '+1-784' },
  { code: 'VE', name: 'Venezuela', region: 'Americas', subregion: 'South America', flag_emoji: '🇻🇪', currency: 'VES', currency_symbol: 'Bs', language: 'Spanish', timezone: 'America/Caracas', calling_code: '+58' },
  { code: 'VN', name: 'Vietnam', region: 'Asia', subregion: 'South-Eastern Asia', flag_emoji: '🇻🇳', currency: 'VND', currency_symbol: '₫', language: 'Vietnamese', timezone: 'Asia/Ho_Chi_Minh', calling_code: '+84' },
  { code: 'VU', name: 'Vanuatu', region: 'Oceania', subregion: 'Melanesia', flag_emoji: '🇻🇺', currency: 'VUV', currency_symbol: 'VT', language: 'French', timezone: 'Pacific/Efate', calling_code: '+678' },
  { code: 'WS', name: 'Samoa', region: 'Oceania', subregion: 'Polynesia', flag_emoji: '🇼🇸', currency: 'WST', currency_symbol: 'T', language: 'Samoan', timezone: 'Pacific/Apia', calling_code: '+685' },
  { code: 'XK', name: 'Kosovo', region: 'Europe', subregion: 'Southern Europe', flag_emoji: '🇽🇰', currency: 'EUR', currency_symbol: '€', language: 'Albanian', timezone: 'Europe/Belgrade', calling_code: '+383' },
  { code: 'YE', name: 'Yemen', region: 'Asia', subregion: 'Western Asia', flag_emoji: '🇾🇪', currency: 'YER', currency_symbol: '﷼', language: 'Arabic', timezone: 'Asia/Aden', calling_code: '+967' },
  { code: 'ZA', name: 'South Africa', region: 'Africa', subregion: 'Southern Africa', flag_emoji: '🇿🇦', currency: 'ZAR', currency_symbol: 'R', language: 'English', timezone: 'Africa/Johannesburg', calling_code: '+27' },
  { code: 'ZM', name: 'Zambia', region: 'Africa', subregion: 'Eastern Africa', flag_emoji: '🇿🇲', currency: 'ZMW', currency_symbol: 'ZK', language: 'English', timezone: 'Africa/Lusaka', calling_code: '+260' },
  { code: 'ZW', name: 'Zimbabwe', region: 'Africa', subregion: 'Eastern Africa', flag_emoji: '🇿🇼', currency: 'ZWL', currency_symbol: 'Z$', language: 'English', timezone: 'Africa/Harare', calling_code: '+263' }
];

const BASE_URL = process.env.FRONTEND_URL || 'http://localhost:5176';

async function seedCountries() {
  console.log(`Seeding ${COUNTRIES.length} countries via API...`);
  
  for (const country of COUNTRIES) {
    try {
      const slug = country.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/-+/g, '-');
      
      // Use backend seeding approach - call DB through a simple insert
      // Since we can't directly run DB queries, let's add endpoint to admin
      console.log(`Would seed: ${country.code} - ${country.name}`);
    } catch(err) {
      console.error(`Error with ${country.name}:`, err.message);
    }
  }
  
  console.log(`\n✅ Done! ${COUNTRIES.length} countries ready for database population.`);
  console.log(`\nTo seed the database, run:`);
  console.log(`1. Start the backend server`);
  console.log(`2. Call POST /api/admin/seed/countries`);
}

// Make this directly insertable
if (require.main === module) {
  seedCountries().catch(console.error);
}

module.exports = { COUNTRIES };