/**
 * Research Service
 * Multi-block destination research pipeline.
 *
 * Each destination is researched as a set of structured content blocks,
 * each generated by a focused AI prompt, reviewed individually, and
 * approved before being served publicly.
 *
 * Blocks: card_summary, safety_brief, solo_suitability, arrival_checklist,
 *         neighbourhood_guidance, after_dark, friction_points, quick_facts, fallback_summary
 */

import logger from './logger.js';
import db from '../db.js';
import { callAI } from './aiOrchestrator.js';
import { geocodeAddress } from './placesService.js';
import axios from 'axios';

const PIPELINE_VERSION = 'v2.0';

// ---------------------------------------------------------------------------
// Block definitions: prompt templates per block type
// ---------------------------------------------------------------------------
const BLOCK_PROMPTS = {
  card_summary: (dest) => `Write a short, honest 2-sentence summary of ${dest} for solo travellers.
Focus on what kind of traveller fits this place and the overall solo-travel experience.
Do NOT use phrases like "vibrant atmosphere" or "something for everyone". Be specific and practical.`,

  safety_brief: (dest) => `Write a practical safety brief for solo travellers visiting ${dest}.
Cover: overall safety level (honest, no fake scores), areas to be aware of, common risks,
time-of-day considerations, transport safety, common scams targeting tourists.
Use bullet points. Keep it under 200 words. Do not invent statistics.`,

  solo_suitability: (dest) => `Assess the solo-travel suitability of ${dest} honestly.
Cover: ease of navigation alone, social opportunities, solo-dining culture, English prevalence,
language barrier, solo-female safety considerations, local attitude to solo travellers.
Write as 3-4 concise paragraphs. Be honest about challenges.`,

  arrival_checklist: (dest) => `Create a practical arrival checklist for a solo traveller arriving in ${dest} for the first time.
Include: airport/station arrival steps, getting a local SIM, transport from airport, where to stay on first night,
local currency advice, first safety steps, apps to download.
Format as a numbered checklist. Be specific to this destination.`,

  neighbourhood_guidance: (dest) => `Describe the key neighbourhoods in ${dest} that matter to solo travellers.
For each neighbourhood include: safety label (safe/mixed/avoid), what it's good for, and any specific notes.
Format as: **[Neighbourhood name]** — [label] — [description]. Cover at least 4 neighbourhoods.`,

  after_dark: (dest) => `Give honest after-dark guidance for solo travellers in ${dest}.
Cover: which areas are safe at night, what to avoid after dark, solo-dining options in the evening,
nightlife culture and whether it's solo-friendly, public transport after midnight.
Keep under 150 words. Be specific.`,

  friction_points: (dest) => `List the most common friction points and problems solo travellers encounter in ${dest}.
For each, give: the problem and a practical mitigation.
Format as a list. Cover 5-7 realistic issues.
Examples of friction points: taxi scams, language barriers, public transport confusion, cultural misunderstandings.`,

  quick_facts: (dest) => `Return a JSON object with quick facts for solo travellers in ${dest}:
{
  "capital_or_main_city": "",
  "currency": "",
  "languages": [],
  "timezone": "",
  "plug_type": "",
  "emergency_number": "",
  "police_number": "",
  "ambulance_number": "",
  "driving_side": "left|right",
  "tap_water_safe": true|false,
  "visa_required_uk": true|false|"depends",
  "visa_notes": ""
}
Return ONLY the JSON object. Do not invent numbers — if unsure, use null.`,

  fallback_summary: (dest) => `Write a brief 1-paragraph fallback summary of ${dest} for solo travellers.
This will be shown when detailed content is not yet available.
Keep it factual, honest, and under 80 words.`,
};

const REQUIRED_BLOCKS = Object.keys(BLOCK_PROMPTS);

// ---------------------------------------------------------------------------
// Utilities
// ---------------------------------------------------------------------------
async function fetchDestinationImage(query) {
  const accessKey = process.env.UNSPLASH_ACCESS_KEY;
  if (!accessKey) {
    logger.warn('[Research] UNSPLASH_ACCESS_KEY missing. Using placeholder.');
    return 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&q=80';
  }
  try {
    const res = await axios.get('https://api.unsplash.com/search/photos', {
      params: { query: `${query} travel landscape`, per_page: 1, orientation: 'landscape', content_filter: 'high' },
      headers: { Authorization: `Client-ID ${accessKey}` }
    });
    return res.data.results[0]?.urls?.regular || 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&q=80';
  } catch (err) {
    logger.error(`[Research] Unsplash fetch failed for ${query}: ${err.message}`);
    return 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&q=80';
  }
}

function estimateQualityScore(content) {
  if (!content || content.length < 50) return 0.1;
  if (content.length < 150) return 0.4;
  if (content.length < 400) return 0.7;
  return 0.9;
}

// ---------------------------------------------------------------------------
// Generate a single content block for a destination
// ---------------------------------------------------------------------------
async function generateContentBlock(destinationId, destinationName, blockType) {
  const promptFn = BLOCK_PROMPTS[blockType];
  if (!promptFn) throw new Error(`Unknown block type: ${blockType}`);

  const requireJson = blockType === 'quick_facts';
  const { response, source } = await callAI(
    'destination_research_section',
    [{ role: 'user', content: promptFn(destinationName) }],
    { maxTokens: 600, requireJson, skipObservability: true, ctx: { destinationName } }
  );

  const qualityScore = estimateQualityScore(response);

  // Upsert content block
  const existing = await db.prepare(
    'SELECT id FROM destination_content_blocks WHERE destination_id = ? AND block_type = ?'
  ).get(destinationId, blockType);

  if (existing) {
    await db.prepare(`
      UPDATE destination_content_blocks SET
        content = ?, prompt_version = ?, ai_quality_score = ?,
        review_status = 'pending', reviewer_id = NULL, reviewed_at = NULL,
        reviewer_notes = NULL, generated_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
      WHERE id = ?
    `).run(response, PIPELINE_VERSION, qualityScore, existing.id);
  } else {
    await db.prepare(`
      INSERT INTO destination_content_blocks
        (destination_id, block_type, content, prompt_version, ai_quality_score, review_status, generated_at, updated_at)
      VALUES (?, ?, ?, ?, ?, 'pending', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    `).run(destinationId, blockType, response, PIPELINE_VERSION, qualityScore);
  }

  logger.info(`[Research] Block '${blockType}' generated for ${destinationName} (score: ${qualityScore}, source: ${source})`);
  return { blockType, qualityScore, source };
}

// ---------------------------------------------------------------------------
// Generate base metadata for a destination (one-shot JSON prompt)
// ---------------------------------------------------------------------------
async function generateBaseMetadata(destinationName) {
  const prompt = `Research "${destinationName}" for a solo travel safety app.
Return ONLY valid JSON (no markdown):
{
  "name": "Full official name",
  "country": "Country name",
  "city": "Primary city/area name",
  "destination_level": "country|city",
  "description": "2-sentence factual overview (no hype)",
  "budget_level": "budget|moderate|luxury",
  "safety_rating": "high|medium|low",
  "solo_friendly_rating": 1-5,
  "emergency_contacts": { "police": "", "ambulance": "", "fire": "" },
  "highlights": ["6 specific solo-friendly experiences"],
  "best_months": ["month names"],
  "fcdo_slug": "url-slug",
  "travel_styles": ["adventure|culture|relaxation|wellness|social|outdoors"],
  "climate": "brief description",
  "advisory_stance": "normal|exercise_caution|advise_against|advise_against_all",
  "solo_fit_tags": ["solo-female-friendly|beginner-safe|budget|english-spoken|backpacker-hub"],
  "best_for_tags": ["culture|food|nightlife|nature|history|beaches|adventure"],
  "region_name": "Region or state name if applicable"
}`;

  const { response } = await callAI(
    'destination_research_section',
    [{ role: 'user', content: prompt }],
    { maxTokens: 800, requireJson: true, skipObservability: true }
  );

  let data;
  try {
    data = typeof response === 'object' ? response : JSON.parse(response);
  } catch (e) {
    const clean = response.replace(/```json|```/g, '').trim();
    data = JSON.parse(clean);
  }
  return data;
}

// ---------------------------------------------------------------------------
// Main pipeline: research a destination (full run)
// ---------------------------------------------------------------------------
export async function researchDestination(destinationName) {
  logger.info(`[Research] Starting pipeline for: ${destinationName}`);

  try {
    // 1. Generate base metadata
    const data = await generateBaseMetadata(destinationName);

    // 2. Geocode
    try {
      const geo = await geocodeAddress(destinationName);
      data.latitude = geo.lat;
      data.longitude = geo.lon;
    } catch (geoErr) {
      logger.warn(`[Research] Geocoding failed: ${geoErr.message}`);
      data.latitude = 0;
      data.longitude = 0;
    }

    // 3. Fetch image
    data.image_url = await fetchDestinationImage(`${data.name} ${data.country}`);

    // 4. Generate slug
    const slug = (data.name || destinationName).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');

    // 5. Upsert destination record
    const existing = await db.prepare('SELECT id FROM destinations WHERE (name = ? AND country = ?) OR slug = ?').get(data.name, data.country, slug);

    let destinationId;
    if (existing) {
      await db.prepare(`
        UPDATE destinations SET
          city = ?, description = ?, budget_level = ?, safety_rating = ?,
          solo_friendly_rating = ?, image_url = ?, fcdo_slug = ?,
          latitude = ?, longitude = ?, emergency_contacts = ?,
          safety_intelligence = ?, highlights = ?, travel_styles = ?,
          climate = ?, best_months = ?, source = 'ai',
          destination_level = COALESCE(?, destination_level),
          publication_status = 'in_progress',
          research_status = 'in_progress',
          research_last_run_at = CURRENT_TIMESTAMP,
          research_pipeline_version = ?,
          advisory_stance = ?,
          solo_fit_tags = ?, best_for_tags = ?, region_name = ?,
          slug = COALESCE(NULLIF(slug, ''), ?),
          title = COALESCE(NULLIF(title, ''), ?),
          updated_at = CURRENT_TIMESTAMP
        WHERE id = ?
      `).run(
        data.city, data.description, data.budget_level, data.safety_rating,
        data.solo_friendly_rating, data.image_url, data.fcdo_slug,
        data.latitude, data.longitude, JSON.stringify(data.emergency_contacts || {}),
        '', JSON.stringify(data.highlights || []), JSON.stringify(data.travel_styles || []),
        data.climate, JSON.stringify(data.best_months || []),
        data.destination_level || null, PIPELINE_VERSION,
        data.advisory_stance || null,
        JSON.stringify(data.solo_fit_tags || []), JSON.stringify(data.best_for_tags || []),
        data.region_name || null, slug, data.name, existing.id
      );
      destinationId = existing.id;
    } else {
      const result = await db.prepare(`
        INSERT INTO destinations (
          name, country, city, description, budget_level, safety_rating,
          solo_friendly_rating, image_url, fcdo_slug, latitude, longitude,
          emergency_contacts, highlights, travel_styles, climate, best_months,
          source, destination_level, publication_status, research_status,
          research_last_run_at, research_pipeline_version, advisory_stance,
          solo_fit_tags, best_for_tags, region_name, slug, title
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'ai', ?, 'in_progress', 'in_progress',
          CURRENT_TIMESTAMP, ?, ?, ?, ?, ?, ?, ?)
      `).run(
        data.name, data.country, data.city, data.description, data.budget_level,
        data.safety_rating, data.solo_friendly_rating, data.image_url, data.fcdo_slug,
        data.latitude, data.longitude, JSON.stringify(data.emergency_contacts || {}),
        JSON.stringify(data.highlights || []), JSON.stringify(data.travel_styles || []),
        data.climate, JSON.stringify(data.best_months || []),
        data.destination_level || 'city', PIPELINE_VERSION,
        data.advisory_stance || null,
        JSON.stringify(data.solo_fit_tags || []), JSON.stringify(data.best_for_tags || []),
        data.region_name || null, slug, data.name,
      );
      destinationId = result.lastInsertRowid;
    }

    // 6. Generate all content blocks
    const blockResults = [];
    for (const blockType of REQUIRED_BLOCKS) {
      try {
        const result = await generateContentBlock(destinationId, data.name, blockType);
        blockResults.push(result);
      } catch (blockErr) {
        logger.error(`[Research] Block '${blockType}' failed for ${data.name}: ${blockErr.message}`);
        blockResults.push({ blockType, qualityScore: 0, error: blockErr.message });
      }
    }

    // 7. Compute overall quality score and update destination
    const avgQuality = blockResults.reduce((sum, b) => sum + (b.qualityScore || 0), 0) / blockResults.length;
    await db.prepare(`
      UPDATE destinations SET
        research_status = 'complete',
        manual_review_required = true,
        manual_review_status = 'pending',
        publication_status = 'needs_review',
        ai_quality_score = ?,
        ai_prompt_version = ?
      WHERE id = ?
    `).run(avgQuality, PIPELINE_VERSION, destinationId);

    logger.info(`[Research] Pipeline complete for ${data.name} — quality: ${avgQuality.toFixed(2)}`);
    return { success: true, data: { ...data, id: destinationId, blockResults, avgQuality } };

  } catch (err) {
    logger.error(`[Research] Pipeline FAILED for ${destinationName}: ${err.message}`);
    return { success: false, error: err.message };
  }
}

// ---------------------------------------------------------------------------
// Regenerate a single content block for an existing destination
// ---------------------------------------------------------------------------
export async function regenerateBlock(destinationId, blockType) {
  const destination = await db.prepare('SELECT id, name FROM destinations WHERE id = ?').get(destinationId);
  if (!destination) throw new Error(`Destination ${destinationId} not found`);

  await generateContentBlock(destinationId, destination.name, blockType);
  return { success: true, destinationId, blockType };
}

// ---------------------------------------------------------------------------
// Stale detection job — marks destinations past content_fresh_until as stale
// ---------------------------------------------------------------------------
export async function markStaleDestinations() {
  try {
    const result = await db.prepare(`
      UPDATE destinations SET
        publication_status = 'stale',
        safety_gate_status = 'pending'
      WHERE publication_status = 'live'
        AND content_fresh_until IS NOT NULL
        AND content_fresh_until < CURRENT_TIMESTAMP
    `).run();
    logger.info(`[Research] Marked ${result.changes} destinations as stale`);
    return result.changes;
  } catch (err) {
    logger.error('[Research] Stale detection failed:', err.message);
    return 0;
  }
}

// ---------------------------------------------------------------------------
// Bulk seed the moderation queue
// ---------------------------------------------------------------------------
export async function seedModerationQueue(list) {
  const results = [];
  for (const name of list) {
    const res = await researchDestination(name);
    results.push({ name, ...res });
  }
  return results;
}

export default {
  researchDestination,
  regenerateBlock,
  seedModerationQueue,
  markStaleDestinations,
};

