import { MapPin, PoundSterling, Navigation, ExternalLink, Clock, Edit2, Trash2, Plus, Zap, CheckCircle2, Camera, Utensils, Moon, Coffee, Info } from 'lucide-react';
import Skeleton from '../Skeleton';
import Button from '../Button';

const getActivityIcon = (type) => {
  switch (type) {
    case 'Sightseeing': return <Camera size={18} />;
    case 'Food & Dining': return <Utensils size={18} />;
    case 'Transport': return <Navigation size={18} />;
    case 'Adventure': return <Zap size={18} />;
    case 'Cultural': return <Info size={18} />;
    case 'Relaxation': return <Coffee size={18} />;
    case 'Nightlife': return <Moon size={18} />;
    default: return <MapPin size={18} />;
  }
};

function TripMainContent({ trip, loading, generating, onEditActivity, onDeleteActivity, onAddActivity, onGenerate }) {
  return (
    <div className="lg:col-span-2">
      {loading ? (
        <div className="space-y-12">
          {[1, 2, 3].map(i => (
            <div key={`skeleton-${i}`} className="relative pl-8 border-l-2 border-base-content/10 pb-4">
              <div className="absolute -left-3 top-0 w-6 h-6 rounded-full bg-base-300 border-2 border-base-100"></div>
              <Skeleton className="h-10 w-48 mb-8" />
              <div className="space-y-4">
                <Skeleton className="h-40 w-full rounded-xl" />
                <Skeleton className="h-40 w-full rounded-xl" />
              </div>
            </div>
          ))}
        </div>
      ) : trip.itinerary && trip.itinerary.length > 0 ? (
        <div className="space-y-12">
          <div className="flex items-center justify-between px-2">
            <h2 className="text-2xl font-black text-base-content">Daily Roadmap</h2>
            <div className="flex items-center gap-2 text-sm font-bold text-base-content/40">
              <CheckCircle2 size={16} className="text-emerald-500" /> Generated by AI
            </div>
          </div>

          {trip.itinerary.map((day) => (
            <div key={day.id} className="relative pl-8 border-l-2 border-base-content/10 pb-4">
              <div className="absolute -left-3 top-0 w-6 h-6 rounded-full bg-base-100 border-2 border-brand-vibrant z-10 flex items-center justify-center">
                <div className="w-2 h-2 rounded-full bg-brand-vibrant"></div>
              </div>

              <div className="mb-8">
                <h3 className="text-2xl font-black text-base-content flex items-baseline gap-3">
                  Day {day.day_number}
                  {day.date && (
                    <span className="text-sm font-bold text-base-content/40">
                      — {new Date(day.date).toLocaleDateString(undefined, { weekday: 'long', month: 'short', day: 'numeric' })}
                    </span>
                  )}
                </h3>
                <div className="flex items-center gap-4 mt-2">
                  {day.notes && <p className="text-brand-accent font-bold text-sm italic">{day.notes}</p>}
                  <button
                    onClick={() => onAddActivity?.(day.id)}
                    className="flex items-center gap-1.5 px-3 py-1 rounded-lg bg-base-200 text-base-content/60 hover:bg-brand-vibrant hover:text-white text-[10px] font-black uppercase tracking-widest transition-all"
                  >
                    <Plus size={12} /> Add Activity
                  </button>
                </div>
              </div>

              <div className="space-y-4">
                {day.activities?.length > 0 ? (
                  day.activities.map((activity) => (
                    <div key={activity.id} className="group relative glass-card p-6 rounded-xl border border-base-content/5 hover:border-brand-vibrant/20 hover:shadow-xl hover:shadow-brand-vibrant/5 transition-all">
                      <div className="flex flex-col md:flex-row gap-6">
                        <div className="w-12 h-12 rounded-xl bg-base-200 flex items-center justify-center text-base-content group-hover:bg-brand-vibrant group-hover:text-white transition-colors flex-shrink-0">
                          {getActivityIcon(activity.type)}
                        </div>

                        <div className="flex-1 space-y-2">
                          <div className="flex justify-between items-start">
                            <div>
                              <div className="flex items-center gap-3">
                                <h4 className="text-xl font-extrabold text-base-content leading-none">{activity.name}</h4>
                                <span className="text-[10px] font-black uppercase tracking-widest px-2 py-0.5 rounded-md bg-base-200 text-base-content/60">{activity.type}</span>
                              </div>
                              <p className="text-sm font-bold text-base-content/40 mt-1 flex items-center gap-1">
                                <MapPin size={14} /> {activity.location}
                              </p>
                            </div>
                            <div className="text-right flex-shrink-0">
                              <p className="text-sm font-black text-base-content">{activity.time || 'Flexible'}</p>
                              {activity.duration_hours && (
                                <p className="text-xs font-bold text-base-content/40">{activity.duration_hours}h duration</p>
                              )}
                            </div>
                          </div>

                          {activity.description && (
                            <p className="text-sm text-base-content/70 font-medium leading-relaxed">{activity.description}</p>
                          )}

                          <div className="flex flex-wrap items-center gap-4 pt-2">
                            {activity.cost > 0 && (
                              <div className="flex items-center gap-1 px-2 py-1 rounded-lg bg-success/10 text-success text-xs font-black">
                                <PoundSterling size={12} /> {activity.cost}
                              </div>
                            )}
                            <a
                              href={`https://www.google.com/maps/search/${encodeURIComponent(activity.name + ' ' + activity.location)}`}
                              target="_blank"
                              rel="noreferrer"
                              className="text-xs font-black text-brand-vibrant hover:underline flex items-center gap-1"
                            >
                              <MapPin size={12} /> View
                            </a>
                            <a
                              href={`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(activity.name + ' ' + (activity.location || ''))}`}
                              target="_blank"
                              rel="noreferrer"
                              className="text-xs font-black text-blue-500 hover:underline flex items-center gap-1"
                            >
                              <Navigation size={12} /> Directions
                            </a>
                            {(activity.type === 'Food & Dining' || activity.type === 'Accommodation') && (
                              <a
                                href={`https://www.booking.com/search.html?ss=${encodeURIComponent(activity.name + ' ' + (activity.location || trip.destination))}`}
                                target="_blank"
                                rel="noreferrer"
                                className="text-xs font-black text-blue-600 hover:underline flex items-center gap-1"
                              >
                                <ExternalLink size={12} /> Book Stay
                              </a>
                            )}
                            {activity.type !== 'Transport' && activity.type !== 'Food & Dining' && (
                              <a
                                href={`https://www.viator.com/search?q=${encodeURIComponent(activity.name)}&location=${encodeURIComponent(trip.destination)}&pid=${import.meta.env.VITE_VIATOR_PID || ''}`}
                                target="_blank"
                                rel="noreferrer"
                                className="text-xs font-black text-[#ff5900] hover:underline flex items-center gap-1"
                              >
                                <ExternalLink size={12} /> Book Tour on Viator
                              </a>
                            )}
                            {activity.bookingInfo && (
                              <div className="text-xs font-bold text-base-content/40 flex items-center gap-1">
                                <Clock size={12} /> {activity.bookingInfo}
                              </div>
                            )}
                          </div>
                        </div>

                        <div className="flex md:flex-col items-center justify-end gap-2 pr-2">
                          <button
                            onClick={() => onEditActivity?.(activity)}
                            className="p-2 text-base-content/20 hover:text-brand-vibrant hover:bg-base-100 rounded-lg transition-all opacity-0 group-hover:opacity-100"
                            title="Edit Activity"
                          >
                            <Edit2 size={18} />
                          </button>
                          <button
                            onClick={() => onDeleteActivity?.(activity.id)}
                            className="p-2 text-base-content/20 hover:text-error hover:bg-base-100 rounded-lg transition-all opacity-0 group-hover:opacity-100"
                            title="Remove Activity"
                          >
                            <Trash2 size={18} />
                          </button>
                        </div>
                      </div>
                    </div>
                  ))
                ) : (
                  <div className="p-10 border-2 border-dashed border-base-content/5 rounded-xl flex flex-col items-center justify-center text-center">
                    <MapPin size={32} className="text-base-content/10 mb-4" />
                    <p className="text-base-content/40 font-bold">No activities fixed for this day yet.</p>
                  </div>
                )}
              </div>
            </div>
          ))}
        </div>
      ) : (
        <div className="h-full min-h-[500px] flex flex-col items-center justify-center glass-card rounded-xl p-12 text-center">
          <div className="w-20 h-20 bg-base-200 rounded-xl flex items-center justify-center mb-8 border border-base-content/10">
            <Zap size={40} className="text-base-content/20" />
          </div>
          <h3 className="text-2xl font-black text-base-content mb-2">Roadmap is Empty</h3>
          <p className="text-base-content/60 font-medium max-w-sm mx-auto mb-10 text-lg">
            Your itinerary hasn&apos;t been designed. Use the AI engine in the sidebar to create your perfect solo trip.
          </p>
          <Button
            onClick={onGenerate}
            disabled={generating}
            variant="primary"
            className="rounded-xl px-12 py-4 font-black btn-premium shadow-2xl"
          >
            {generating ? 'Processing DNA...' : 'Start AI Generation'}
          </Button>
        </div>
      )}
    </div>
  );
}

export default TripMainContent;
